### ISSUE TITLE
check if the mail is valid or not

### ISSUE THREAD

**Issue by sandeshghanta** [sandeshghanta/Status_Update_Bot#2]

**Comment by riddhik84** [comment]
Can I work on it?

**Comment by Aniketh01** [comment]
Hi @sandeshghanta, 

Can I fix this issue up?

**Comment by Aniketh01** [comment]
> Yeah sure you can work on this issue.

Thanks. Here is the Pull request :) #3

**Comment by sandeshghanta** [comment]
> > Yeah sure you can work on this issue.
> 
> Thanks. Here is the Pull request :) #3

Looked into the pull request. It fixes the issue. Thanks for helping me out.
