### ISSUE TITLE
Help needed to format README.MD

### ISSUE THREAD

**Issue by sandeshghanta** [sandeshghanta/Status_Update_Bot#5]
The current README is not formatted properly. Please format it to make it look better

**Comment by Barathwaja** [comment]
@sandeshghanta I'll do it.

**Comment by Barathwaja** [comment]
@sandeshghanta you haven't mentioned how to configure / installation steps? can you share that ?

**Comment by sandeshghanta** [comment]
I will update those later. Right now you need not concern yourself with it.

**Comment by Barathwaja** [comment]
PR #6
